### ISSUE TITLE
Request result with chunked data

### ISSUE THREAD

**Issue by cachila** [RisingStack/example-http-timings#1]
Hello, first of all I want to thank you for this code, it has helped me a lot.

I am having a problem and it is associated with chunked responses. 
For example, when I do a request to [https://http2.mlstatic.com/resources/deals/exhibitors_resources/mlu-home-desktop-slider-picture-fa35cb9b-1d6f-4e09-a581-7aac2d8ea0ee.jpg], the response headers are 

- "content-type": "image/jpeg",
- "server": "Tengine",
- "last-modified": "Fri, 16 Mar 2018 21:30:25 GMT",
- "etag": "6297adf91b734e4749ddf21cee0c2b2e",
- "cache-control": "public, max-age=315360000",
- "access-control-allow-origin": "*",
- "date": "Tue, 27 Mar 2018 20:46:26 GMT",
- **"transfer-encoding": "chunked",**
- "connection": "close, Transfer-Encoding"

As far as I understand, it should return the whole content as the `res.on('end')` is called when all data is consumed. Am I right?

I saw the comment `"in our case we consume it see: res.on('data')"` but I don't get why I don't get the whole content.

Thanks

**Comment by Shadowbeetle** [comment]
Hi,

You actually get all the data, but it is pretty difficult to concatenate binary data chunk by chunk in Node.js. You are better off writing it to a WriteStream instead.

If you replace this:
```js
res.on('data', chunk => {
  const buf = Buffer.from(chunk, 'binary')
  responseBody = Buffer.concat([responseBody, buf])
})
```

with this:

```js
const fs = require('fs')
const file = fs.createWriteStream('testFile.jpg')
res.pipe(file)
```

you'll see that you have downloaded the whole file all right and you get the proper timings as well.

**Comment by cachila** [comment]
Thanks for the response @Shadowbeetle .

I am only interested in timings and content-length, so the data itself doest matter to me now.

The main issue is that there are some files (like https://http2.mlstatic.com/resources/deals/exhibitors_resources/mlu-home-desktop-slider-picture-fa35cb9b-1d6f-4e09-a581-7aac2d8ea0ee.jpg) that have not the **content-lenght** header in the last chunk, as it should AFAIK. 

I could resolve this by calculating the content length myself with:

```
let contentLength = 0;
res.on('data', (chunk) => {
  contentLength += Buffer.byteLength(chunk);
  responseBody += chunk;
});

res.on('end', () => {
  if (res.headers['content-length'] === undefined){
    res.headers['content-length'] = contentLength;
  }
  eventTimes.endAt = process.hrtime();
  callback(null, {
    headers: res.headers,
    timings: getTimings(eventTimes),
    body: responseBody
  });
});
```

It turned out to be pretty accurate.

I am closing this issue because is not a problem with the code, it is just that these files does no respect the RFC and does not send the content-length header.

Thanks again
